/**
 * Fuxi Plan Template
 *
 * The markdown template structure for diagnostic plans generated by Fuxi (Phase 1).
 * Compliant with Intelligent OM Diagnosis System Architecture.
 */

export const FUXI_PLAN_TEMPLATE = `## Plan Structure

Generate plan to: \`~/.dayu/plans/{timestamp}_{plan_id}.md\`

\`\`\`markdown
# 诊断排查方案: {Plan Title}

## 1. 故障场景 (Fault Scenario)

- **场景类型 (Mode)**: [在线诊断 (Online) | 离线分析 (Offline)]
- **连接信息 (Connection)**:
  - **Target**: [IP Address / Log Path]
  - **Access**: [SSH User / Jump Server / Local Analysis]

## 2. 故障澄清 (Issue Clarification)

- **用户原始描述**:
  > {User Query}

- **经过交互确认的完整故障现象 (Verified Symptom)**:
  > {Detailed Symptom Description}

- **影响范围 (Impact)**:
  - {Scope Description}

## 3. 前期检测结果 (Pre-check Results)

- **环境可达性 (Reachability)**: [Pass/Fail]
- **基础环境信息 (Basic Info)**:
  - **OS**: {OS Version}
  - **Kernel**: {Kernel Version}
- **数据完备性 (Data Availability)**:
  - [ ] 故障日志: {Log Type} (Path: {Path})
  - [ ] 核心转储: {Dump Type} (Path: {Path})

## 4. 诊断模型构建 (Diagnostic Model)

### 现象-模式-根因 假设树

| ID | 故障现象 (Symptom) | 故障模式 (Failure Mode) | 潜在原因 (Root Cause) | 验证手段 (Verification) | 优先级 |
|----|-------------------|----------------------|----------------------|----------------------|-------|
| T1 | {Symptom}         | {Mode}               | {Root Cause}         | {Tool/Command}       | High  |
| T2 | ...               | ...                  | ...                  | ...                  | Med   |

---

## 5. 任务元数据 (JSON Metadata)

\`\`\`json
{
  "plan_id": "{timestamp}_{id}",
  "created_at": "{ISO Date}",
  "mode": "{online|offline}",
  "target": "{ip_or_path}",
  "tasks": [
    {
      "id": "T1",
      "symptom": "{Symptom}",
      "failure_mode": "{Mode}",
      "root_cause": "{Root Cause}",
      "verification": "{Tool/Command}",
      "priority": "high"
    },
    {
      "id": "T2",
      "symptom": "...",
      "failure_mode": "...",
      "root_cause": "...",
      "verification": "...",
      "priority": "medium"
    }
  ]
}
\`\`\`
\`\`\`
`
