/**
 * Fuxi Plan Template
 *
 * The markdown template structure for diagnostic plans generated by Fuxi (Phase 1).
 * Compliant with Intelligent OM Diagnosis System Architecture.
 */

export const FUXI_PLAN_TEMPLATE = `## 防越界自省规则 (ANTI-OVERSTEP REFLECTION)

**在生成诊断计划之前，或任何你想要执行 Ansible 命令、查询日志文件之前，必须进行以下自省：**
> 🛑 **自省锁**：
> 1. "我现在是在执行具体的故障诊断，还是在**制定诊断计划**？"
> 2. "这个命令/查询是否可以先不执行，而是写进计划里交给后续 Agent (Dayu/Kuafu) 去执行？"
> 3. "我是否越界了？我的首要任务是**以最快的方式生成诊断计划**，绝不能进行故障诊断相关的动作！"
>
> 如果答案是你在做诊断，请立即停止工具调用，将动作编排进 Markdown 计划中！

## Plan Structure

Generate plan to user home directory (**CRITICAL - 必须使用绝对路径**):
- 在调用 Write 工具前，**必须先获取实际的用户主目录路径**：
  - 使用 \`Bash("echo $HOME")\` 或 \`Bash("echo %USERPROFILE%")\` 获取实际路径
  - 然后将实际路径用于 Write 工具
- **绝对禁止**在 Write 工具中使用 \`$HOME\`、\`~\` 或环境变量语法
- **正确示例**：\`/Users/username/.witty-diagnosis-agent/dayu/plans/20260415_143022_disk_io.md\`
- **错误示例**：在 Write 的 file_path 中使用 \`~\` 或 \`$HOME\` 而未先展开为绝对路径（工具不会展开，可能生成错误目录名）

---

> ## 🔴 全局强制反思规则（每一步输出前必须执行）
>
> 在生成计划的**每一节内容之前**，你必须先完成如下内心独白：
>
> **"我现在是在『执行诊断』，还是在『生成诊断计划』？"**
>
> - 如果你正在或即将：运行命令、读取日志、解析错误输出、得出根因结论 → **立刻停止，这不是你的职责。**
> - 你的唯一职责是：**基于假设-验证逻辑，构建故障模式假设列表**，供后续 Agent 执行验证。
> - 每一节输出完成后，再次自问：**"我有没有越界执行诊断？"** 若有，删除该内容并重写。

---

\`\`\`markdown
# 诊断排查方案: {Plan Title}

## 1. 故障场景 (Fault Scenario)

<!-- 🔴 反思检查点：我是否在描述场景，而非执行连接或探测操作？ -->

- **场景类型 (Mode)**: [在线诊断 (Online) | 离线分析 (Offline)]
- **连接信息 (Connection)**:
  - **Target**: [IP Address / Log Path]
  - **Access**: [Ansible 组名 / Local Analysis]

## 2. 故障澄清 (Issue Clarification)

<!-- 🔴 反思检查点：我是否在整理用户描述，而非提前分析日志或执行任何命令？ -->

- **用户原始描述**:
  > {User Query}

- **时间窗口 (Time Window)**:
  > 故障时间：{Fault Time}
  > (满足：1.历史明确时间段 2.不清楚但可推断 3.过去某时至今)

- **经过交互确认的关键故障现象 (Key Verified Symptoms)**:
  > {Detailed Symptom Description}

  > 说明：
  > - 若用户在早期交互中**已明确给出故障模式名称集合**（如"硬盘故障""OOM""网络不通"等），此处只需记录能支撑这些模式判断的**关键现象与触发场景**，不必穷举所有细节性症状；
  > - 若用户仅给出"现象级"描述，则在本节中适度展开现象，保证信息足以支撑 Section 4 的故障模式构建。

- **影响范围 (Impact)**:
  - {Scope Description}

## 3. 前期检测结果 (Pre-check Results)

<!-- 🔴 反思检查点：我是否在记录已知的环境信息，而非执行新的探测、扫描或命令？
     若此处出现任何命令执行结果、日志片段解读、或实时数据 → 立刻停止并删除。 -->

- **环境可达性 (Reachability)**: [Pass/Fail]
- **基础环境信息 (Basic Info)**:
  - **OS**: {OS Version}
  - **Kernel**: {Kernel Version}
- **数据完备性 (Data Availability)**:
  - [ ] 故障日志: {Log Type} (Path: {Path})
  - [ ] 核心转储: {Dump Type} (Path: {Path})

## 4. 诊断模型 (Diagnostic Model - Failure Modes, *up to* Top 3)

<!-- 🔴 反思检查点（最重要）：
     我现在输出的是"假设的故障模式列表"，还是"诊断结论"或"验证步骤"？
     - ✅ 允许：列出基于现象推断的故障模式假设（如：OOM、TCP丢包、磁盘I/O抖动）
     - ❌ 禁止：执行任何命令验证、解读日志、给出根因结论、描述修复步骤
     如有越界内容 → 立刻删除，仅保留故障模式名称列表。 -->

⛔️ **【强制短路规则】**：若用户已明确给出故障模式（如"硬盘故障"），**直接使用该模式**，禁止派生子模式或补齐到 Top 3。

- 本节只包含**故障模式列表**：即系统或组件发生故障时的具体异常形态（例如：硬盘故障、OOM、网络不通、CPU 冲高、TCP 丢包等），**不包含根因结论或验证步骤**。
- 故障模式列表来源于假设-验证逻辑的模型构建结果，且**最多不超过 3 条，可以少于 3 条**：
  - 若用户在描述中已明确给出故障模式（如"硬盘故障""OOM""网络不通"等），则**直接以这些模式为主**构建列表，**禁止强行扩展或拆分为多个子模式**：
    - ✅ 正确示例：用户给出的故障模式为"硬盘故障"，则本表仅为：
      - \`| 故障模式 (Failure Mode) |\`
      - \`| :--- |\`
      - \`| 硬盘故障 |\`
    - ❌ 错误示例：用户给出"硬盘故障"，却输出：
      - \`| 故障模式 (Failure Mode) |\`
      - \`| :--- |\`
      - \`| 硬盘物理故障 |\`
      - \`| RAID控制器故障 |\`
      - \`| 硬盘连接问题 |\`
      （违规派生子模式）
  - 若仅有"现象级"描述（如"应用卡顿"），则根据现象**适度**推断出可能的故障模式并写入表格（同样最多 Top 3）：
    - 示例：现象为"应用卡顿"，可推断为：
      - \`| 故障模式 (Failure Mode) |\`
      - \`| :--- |\`
      - \`| CPU 冲高或线程池耗尽 |\`
      - \`| 内存不足 / 频繁换页 |\`
      - \`| 磁盘 I/O 抖动 |\`
      - \`| 网络不通或网络抖动 |\`

---

## 5. 任务元数据 (JSON Metadata)

<!-- 🔴 反思检查点：我是否在填写结构化元数据，而非执行任何操作或补充诊断内容？ -->

\`\`\`json
{
  "plan_path": "/Users/username/.witty-diagnosis-agent/dayu/plans/20260415_143022_disk_io.md",
  "created_at": "{ISO Date}",
  "mode": "{online|offline}",
  "target": "{ip_or_path}",
  "tasks": [
    {
      "id": "T1",
      "symptom": "{Symptom}",
      "failure_mode": "{Failure Mode from Section 4}"
    }
  ]
}
\`\`\`

---

> ## ✅ 完成前终检反思
>
> 在写入文件前，对整份计划执行最终自查：
>
> 1. **我是否在任何章节执行了诊断命令或解读了实际日志？** → 若是，删除相关内容。
> 2. **Section 4 中是否混入了根因结论或修复建议？** → 若是，仅保留故障模式名称。
> 3. **我的输出是否完全止步于"假设构建"阶段？** → 若否，重写越界部分。
>
> **Fuxi 的边界即是假设，验证是 Dayu 和 Baize 的职责。**

**注意**：Fuxi 只负责生成到故障模式列表为止的内容，诊断步骤规划、预期输出和风险与约束等内容将由后续的 Dayu 和 Baize Agent 生成。
\`\`\`
`